---
# tasks file for roles

- name: create role
  vcd_roles:
    user: acmeadmin
    password: ******
    org: Acme
    role_name: sample_role_2
    role_description: sample role
    role_rights:
      - "Catalog: Import Media from vSphere"
    state: present
  register: output

- name: create role output
  debug:
    msg: '{{ output }}'

- name: update role
  vcd_roles:
    user: acmeadmin
    password: *****
    org: Acme
    role_name: sample_role_2
    role_rights:
      - "Organization vDC Distributed Firewall: View Rules"
    state: update
  register: output

- name: update role output
  debug:
    msg: '{{ output }}'

- name: list roles
  vcd_roles:
    user: acmeadmin
    password: *****
    org: Acme
    operation: list_roles
  register: output

- name: list roles output
  debug:
    msg: '{{ output }}'

- name: list rights
  vcd_roles:
    user: acmeadmin
    password: *****
    org: Acme
    operation: list_rights
  register: output

- name: list rights output
  debug:
    msg: '{{ output }}'

- name: delete role
  vcd_roles:
    user: acmeadmin
    password: *****
    org: Acme
    role_name: sample_role_2
    state: absent
  register: output

- name: delete role output
  debug:
    msg: '{{ output }}'
